### ISSUE TITLE
crashes when opening

### ISSUE THREAD

**Issue by ire4ever1190** [HamletDuFromage/switch-cheats-updater#1]
When I open the nro through the hbmenu on my switch it crashes with code 2168-0000 (0xa8)

I am running 9.2.0 with atmosphere 0.10.4

**Comment by HamletDuFromage** [comment]
Could you please attach the crash log from /atmosphere/fatal_reports?

**Comment by ire4ever1190** [comment]
Crash log didn't generate for some reason. I then deleted and reinstalled from homebrew store and that fixed. I must have installed it incorrectly
