### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by OkayThereBud** [HamletDuFromage/switch-cheats-updater#2]
When I hit A to download and update cheat files the screen just goes black and nothing seems to happen.

**Comment by HamletDuFromage** [comment]
Could you tell me more? Current FW update and CFW, maybe a screenshot or a picture of the blank screen you're mentioning. Does it crash the app or does it just stay on a blank screen?

Thank you :)

**Comment by blackheartme88** [comment]
same thing happened to me, FW 9.2.0, SXOS 2.9.4, after finishing download the cheat, the screen just went blank , waited few minutes nothing happened, i can still press home button to go back to home, the app didnt crashed just went blank and stayed like that

**Comment by OkayThereBud** [comment]
@HamletDuFromage Its the same as blackheartme88 FW 9.2.0, and SXOS 2.9.4 and I can confirm what he is saying is happening to me as well. I feel like a picture of the black screen will be useless.

**Comment by HamletDuFromage** [comment]
Yes, I had another user reporting the same issue. It seems to be SXOS specific and I don't have SXOS... I'll try to investigate but I have a hard time seeing when it happens. If one of you is willing to help me fix that, you can message me at @Simple#8155 on discord

**Comment by HamletDuFromage** [comment]
Fixed on 1.1.3. Thanks a ton to @StevenLeonK for his help
