### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 7h3Cub3** [HamletDuFromage/switch-cheats-updater#4]
Hello, thanks for this awesome tool, im getting the following error when i try to download or list the installed games, first time i get the error and then 2nd time it's unable to find any installed games, i have to restart the whole app to get games detected again, but it still make the error and rince & repeat.

![2020052114454700-387D3132CAF52D748486E541E354E474_blur](https://user-images.githubusercontent.com/17658582/82560783-61f14400-9b72-11ea-871f-637b2eb27c01.jpg)

Any ideas why it would do that ? Thanks.

**Comment by HamletDuFromage** [comment]
Hey, I think I see what it is that causes the problem, but do you mind giving me the title id of the game that causes the `nsGetApplicationControlData()` error? That way I can try to replicate
Also what CFW are you on?

**Comment by 7h3Cub3** [comment]
Im using SXOS 2.9.4, title ID is 0100E65002BB8000

**Comment by HamletDuFromage** [comment]
Would you mind contacting me on discord @simple#8155, or somewhere else of your liking? I couldn't replicate the issue but I might have fixed it still. If you're down, you could help me test

**Comment by 7h3Cub3** [comment]
sure i'll contact you tomorrow !

PS : i think i found the reason, seems like the datas for this game was corrupted, after using the check corruption, it doesn't do it anymore.

PS2 : i tried to add you on discord it wasn't working, i tried again with a capital S and it worked :) i'll DM you tomorrow if you need additionnal infos
