### ISSUE TITLE
Updater will not update again if swapping between sysnand/emunand

### ISSUE THREAD

**Issue by Frolie** [HamletDuFromage/switch-cheats-updater#8]
When updating cheats it will only add cheats for installed games but the games installed is different between sysnand/emunand and if trying to update both the updater will say already up to date nothing else to do while missing the other games. Maybe add a way to force update or something?

**Comment by HamletDuFromage** [comment]
I might add that. As a workaround, you can delete `version.dat` in `config/cheats-updater` and it will fetch the cheats again. Or just wait for a day and it will grab the newer version of the archive
